name: Publish Package to npmjs
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@camiha'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: install node dependencies
        run: pnpm install
      - name: build package
        run: pnpm build
      - name : publish package
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}